import { EnrollmentData } from './types';

export const MOCK_ENROLLMENTS: EnrollmentData[] = [
  {
    studentInfo: {
      firstName: 'Juan',
      middleName: 'D.',
      lastName: 'Dela Cruz',
      age: '20',
      gender: 'Male',
      address: 'Montalban, Rizal',
      contactNumber: '09123456789',
      email: 'juan@example.com',
      birthday: '2004-05-15',
      studentId: '2022-00123',
      yearLevel: '2nd Year',
    },
    type: 'Regular',
    course: 'BSIT',
    status: 'Enrolled',
    enrolledAt: '2026-05-01 10:30',
  },
  {
    studentInfo: {
      firstName: 'Maria',
      middleName: 'S.',
      lastName: 'Santos',
      age: '19',
      gender: 'Female',
      address: 'Rodriguez, Rizal',
      contactNumber: '09987654321',
      email: 'maria@example.com',
      birthday: '2005-08-20',
      studentId: '2023-00456',
      yearLevel: '1st Year',
    },
    type: 'Regular',
    course: 'BSCPE',
    status: 'Enrolled',
    enrolledAt: '2026-05-02 14:15',
  },
  {
    studentInfo: {
      firstName: 'Pedro',
      middleName: 'A.',
      lastName: 'Penduko',
      age: '21',
      gender: 'Male',
      address: 'San Mateo, Rizal',
      contactNumber: '09112233445',
      email: 'pedro@example.com',
      birthday: '2003-12-10',
      studentId: '2021-00789',
      yearLevel: '3rd Year',
    },
    type: 'Irregular',
    course: 'BS ENTREP',
    status: 'Pending',
    enrolledAt: '2026-05-05 09:00',
  },
  {
    studentInfo: {
      firstName: 'Elena',
      middleName: 'G.',
      lastName: 'Reyes',
      age: '22',
      gender: 'Female',
      address: 'Montalban, Rizal',
      contactNumber: '09556677889',
      email: 'elena@example.com',
      birthday: '2002-03-25',
      studentId: '2020-00321',
      yearLevel: '4th Year',
    },
    type: 'Returnee',
    course: 'BEEd GEN',
    status: 'Enrolled',
    enrolledAt: '2026-05-06 11:45',
  },
  {
    studentInfo: {
      firstName: 'Ricardo',
      middleName: 'M.',
      lastName: 'Dalisay',
      age: '20',
      gender: 'Male',
      address: 'Manila',
      contactNumber: '09223344556',
      email: 'ricardo@example.com',
      birthday: '2004-11-05',
      studentId: '2022-00999',
      yearLevel: '2nd Year',
    },
    type: 'Regular',
    course: 'BTLED-ICT',
    status: 'Approved',
    enrolledAt: '2026-05-07 08:30',
  }
];

export const CHART_DATA = [
  { name: 'Mon', count: 12 },
  { name: 'Tue', count: 18 },
  { name: 'Wed', count: 15 },
  { name: 'Thu', count: 25 },
  { name: 'Fri', count: 32 },
  { name: 'Sat', count: 10 },
  { name: 'Sun', count: 5 },
];
